#spring:
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    database: postgresql
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#  datasource:
#    url: jdbc:postgresql://localhost:5432/secondary_db
#    username: postgres
#    password: password
#    driver-class-name: org.postgresql.Driver
#    hikari:
#      connection-timeout: 30000
#      maximum-pool-size: 10
